######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 7 11:21:00 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keypad.h
SOURCES += keypad.cpp main.cpp
